In [4]:
from datadownloader.Stock import Stock

# Stock history price and current basic information:

In [5]:
# default is freq='daily'
aapl = Stock('AAPL')
aapl.get_history()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
date,,,,,,,,
2000-07-03,52.13,54.3100,52.13,53.31,3.2962,1264800.0,0.0,1.0
2000-07-05,53.25,55.1900,50.75,51.63,3.1923,4736000.0,0.0,1.0
2000-07-06,52.50,52.9400,49.63,51.81,3.2034,5527600.0,0.0,1.0
2000-07-07,52.59,54.8100,52.13,54.44,3.3661,4707200.0,0.0,1.0
2000-07-10,54.09,58.2500,53.75,57.13,3.5324,7103500.0,0.0,1.0
...,...,...,...,...,...,...,...,...
2020-06-26,364.41,365.3200,353.02,353.63,353.6300,51314211.0,0.0,1.0
2020-06-29,353.25,362.1736,351.28,361.78,361.7800,32661519.0,0.0,1.0
2020-06-30,360.08,365.9800,360.00,364.80,364.8000,35055821.0,0.0,1.0
2020-07-01,365.12,367.3600,363.91,364.11,364.1100,27690454.0,0.0,1.0
2020-07-02,367.85,370.4700,363.64,364.11,364.1100,28814516.0,0.0,1.0

In [6]:
aapl.get_balance_sheet()

,Cash On Hand,Receivables,Inventory,Pre-Paid Expenses,Other Current Assets,Total Current Assets,"Property, Plant, And Equipment",Long-Term Investments,Goodwill And Intangible Assets,Other Long-Term Assets,...,Long Term Debt,Other Non-Current Liabilities,Total Long Term Liabilities,Total Liabilities,Common Stock Net,Retained Earnings (Accumulated Deficit),Comprehensive Income,Other Share Holders Equity,Share Holder Equity,Total Liabilities And Share Holders Equity
Date,,,,,,,,,,,,,,,,,,,,,
2005-03-31,7057.0,888.0,164.0,None,601.0,9007.0,742.0,NaN,113.0,249.0,...,NaN,373.0,373.0,3725.0,3195.0,3255.0,6.0,None,6386.0,10111.0
2005-06-30,7526.0,827.0,193.0,None,496.0,9376.0,764.0,NaN,109.0,239.0,...,NaN,544.0,544.0,3667.0,3299.0,3575.0,9.0,None,6821.0,10488.0
2005-09-30,8261.0,895.0,165.0,None,648.0,10300.0,817.0,NaN,96.0,303.0,...,NaN,601.0,601.0,4088.0,3564.0,3925.0,NaN,None,7428.0,11516.0
2005-12-31,8707.0,1331.0,244.0,None,1409.0,12162.0,855.0,NaN,93.0,1071.0,...,NaN,741.0,741.0,5801.0,3815.0,4570.0,-5.0,None,8380.0,14181.0
2006-03-31,8226.0,861.0,204.0,None,1536.0,11286.0,1005.0,NaN,110.0,1510.0,...,NaN,773.0,773.0,5229.0,4014.0,4673.0,-5.0,None,8682.0,13911.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-31,80092.0,26278.0,4884.0,None,12092.0,123346.0,38746.0,145319.0,NaN,34587.0,...,90201.0,52165.0,142366.0,236138.0,42801.0,64558.0,-1499.0,None,105860.0,341998.0
2019-06-30,94614.0,26474.0,3355.0,None,10530.0,134973.0,37636.0,115996.0,NaN,33634.0,...,84936.0,51143.0,136079.0,225783.0,43371.0,53724.0,-639.0,None,96456.0,322239.0
2019-09-30,100557.0,45804.0,4106.0,None,12352.0,162819.0,37378.0,105341.0,NaN,32978.0,...,91807.0,50503.0,142310.0,248028.0,45174.0,45898.0,-584.0,None,90488.0,338516.0
2019-12-31,107162.0,39946.0,4097.0,None,12026.0,163231.0,37031.0,99899.0,NaN,40457.0,...,93078.0,55848.0,148926.0,251087.0,45972.0,43977.0,-418.0,None,89531.0,340618.0
2020-03-31,94051.0,30677.0,3334.0,None,15691.0,143753.0,35889.0,98793.0,NaN,41965.0,...,89086.0,56795.0,145881.0,241975.0,48032.0,33182.0,-2789.0,None,78425.0,320400.0

In [7]:
aapl.get_income_statement()

,Revenue,Cost Of Goods Sold,Gross Profit,Research And Development Expenses,SG&A Expenses,Other Operating Income Or Expenses,Operating Expenses,Operating Income,Total Non-Operating Income/Expense,Pre-Tax Income,...,Other Income,Income From Continuous Operations,Income From Discontinued Operations,Net Income,EBITDA,EBIT,Basic Shares Outstanding,Shares Outstanding,Basic EPS,EPS - Earnings Per Share
Date,,,,,,,,,,,,,,,,,,,,,
2005-03-31,3243.0,2275.0,968.0,119.0,447.0,None,2841.0,402.0,33.0,435.0,...,None,290.0,None,290.0,443.0,402.0,5657.204,5999.077,0.0514,0.0486
2005-06-30,3520.0,2476.0,1044.0,145.0,473.0,None,3094.0,426.0,46.0,472.0,...,None,319.0,None,319.0,472.0,426.0,5705.644,6025.621,0.0557,0.0529
2005-09-30,3678.0,2644.0,1034.0,148.0,474.0,None,3266.0,412.0,60.0,472.0,...,None,424.0,None,424.0,463.0,412.0,5659.073,5998.146,0.0743,0.0700
2005-12-31,5749.0,4185.0,1564.0,182.0,632.0,None,4999.0,750.0,81.0,831.0,...,None,565.0,None,565.0,802.0,750.0,5815.467,6119.449,0.0971,0.0929
2006-03-31,4359.0,3062.0,1297.0,176.0,592.0,None,3830.0,529.0,76.0,605.0,...,None,410.0,None,410.0,579.0,529.0,5886.370,6149.759,0.0700,0.0671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-31,58015.0,36194.0,21821.0,3948.0,4458.0,None,44600.0,13415.0,378.0,13793.0,...,None,11561.0,None,11561.0,16455.0,13415.0,4674.071,4700.646,2.4700,2.4600
2019-06-30,53809.0,33582.0,20227.0,4257.0,4426.0,None,42265.0,11544.0,367.0,11911.0,...,None,10044.0,None,10044.0,14477.0,11544.0,4570.633,4601.380,2.2000,2.1800
2019-09-30,64040.0,39727.0,24313.0,4110.0,4578.0,None,48415.0,15625.0,502.0,16127.0,...,None,13686.0,None,13686.0,18804.0,15625.0,4617.834,4648.913,3.0800,3.0700
2019-12-31,91819.0,56602.0,35217.0,4451.0,5197.0,None,66250.0,25569.0,349.0,25918.0,...,None,22236.0,None,22236.0,28385.0,25569.0,4415.040,4454.604,5.0400,4.9900
2020-03-31,58313.0,35943.0,22370.0,4565.0,4952.0,None,45460.0,12853.0,282.0,13135.0,...,None,11249.0,None,11249.0,15639.0,12853.0,4360.101,4404.691,2.5800,2.5500

In [8]:
aapl.get_cash_flow_statement()

,Net Income/Loss,Total Depreciation And Amortization - Cash Flow,Other Non-Cash Items,Total Non-Cash Items,Change In Accounts Receivable,Change In Inventories,Change In Accounts Payable,Change In Assets/Liabilities,Total Change In Assets/Liabilities,Cash Flow From Operating Activities,...,Net Current Debt,Debt Issuance/Retirement Net - Total,Net Common Equity Issued/Repurchased,Net Total Equity Issued/Repurchased,Total Common And Preferred Stock Dividends Paid,Financial Activities - Other,Cash Flow From Financial Activities,Net Cash Flow,Stock-Based Compensation,Common Stock Dividends Paid
Date,,,,,,,,,,,,,,,,,,,,,
2005-09-30,1328.0,179.0,536.0,715.0,-121.0,-64.0,328.0,349.0,492.0,2535.0,...,NaN,NaN,543.0,543.0,NaN,NaN,543.0,522.0,49.0,NaN
2006-09-30,1989.0,225.0,231.0,456.0,-357.0,-105.0,1611.0,-1374.0,-225.0,2220.0,...,NaN,NaN,318.0,318.0,NaN,6.0,324.0,2901.0,163.0,NaN
2007-09-30,3495.0,327.0,327.0,654.0,-385.0,-76.0,1494.0,288.0,1321.0,5470.0,...,NaN,NaN,365.0,365.0,NaN,374.0,739.0,2960.0,242.0,NaN
2008-09-30,6119.0,496.0,936.0,1432.0,-785.0,-163.0,596.0,2397.0,2045.0,9596.0,...,NaN,NaN,483.0,483.0,NaN,633.0,1116.0,2523.0,516.0,NaN
2009-09-30,8235.0,734.0,1750.0,2484.0,-939.0,54.0,92.0,233.0,-560.0,10159.0,...,NaN,NaN,475.0,475.0,NaN,188.0,663.0,-6612.0,710.0,NaN
2010-09-30,14013.0,1027.0,2319.0,3346.0,-2142.0,-596.0,6307.0,-2333.0,1236.0,18595.0,...,NaN,NaN,912.0,912.0,NaN,345.0,1257.0,5998.0,879.0,0.0
2011-09-30,25922.0,1814.0,4036.0,5850.0,143.0,275.0,2515.0,2824.0,5757.0,37529.0,...,NaN,NaN,831.0,831.0,NaN,613.0,1444.0,-1446.0,1168.0,0.0
2012-09-30,41733.0,3277.0,6145.0,9422.0,-5551.0,-15.0,4467.0,800.0,-299.0,50856.0,...,NaN,NaN,665.0,665.0,-2488.0,125.0,-1698.0,931.0,1740.0,-2488.0
2013-09-30,37037.0,6757.0,3394.0,10151.0,-2172.0,-973.0,2340.0,7283.0,6478.0,53666.0,...,NaN,16896.0,-22330.0,-22330.0,-10564.0,-381.0,-16379.0,3513.0,2253.0,-10564.0
2014-09-30,39510.0,7946.0,5210.0,13156.0,-4232.0,-76.0,5938.0,5417.0,7047.0,59713.0,...,6306.0,18266.0,-44270.0,-44270.0,-11126.0,-419.0,-37549.0,-415.0,2863.0,-11126.0
2015-09-30,53394.0,11257.0,5353.0,16610.0,417.0,-238.0,5001.0,6082.0,11262.0,81266.0,...,2191.0,29305.0,-34710.0,-34710.0,-11561.0,-750.0,-17716.0,7276.0,3586.0,-11561.0
2016-09-30,45687.0,10505.0,9634.0,20139.0,527.0,217.0,2117.0,-2456.0,405.0,66231.0,...,-397.0,22057.0,-30797.0,-30797.0,-12150.0,NaN,-20890.0,-636.0,4210.0,-12150.0
2017-09-30,48351.0,10157.0,10640.0,20797.0,-2093.0,-2723.0,8966.0,-9073.0,-4923.0,64225.0,...,3852.0,29014.0,-32345.0,-32345.0,-12769.0,-1874.0,-17974.0,-195.0,4840.0,-12769.0
2018-09-30,59531.0,10903.0,-27694.0,-16791.0,-5322.0,828.0,9175.0,30013.0,34694.0,77434.0,...,-37.0,432.0,-72069.0,-72069.0,-13712.0,-2527.0,-87876.0,5624.0,5340.0,-13712.0
2019-09-30,55256.0,12547.0,5076.0,17623.0,245.0,-289.0,-1923.0,-1521.0,-3488.0,69391.0,...,-5977.0,-7819.0,-66116.0,-66116.0,-14119.0,-2922.0,-90976.0,24311.0,6068.0,-14119.0

In [9]:
aapl.get_financial_ratios(freq='A')

,Current Ratio,Long-term Debt / Capital,Debt/Equity Ratio,Gross Margin,Operating Margin,EBIT Margin,EBITDA Margin,Pre-Tax Profit Margin,Net Profit Margin,Asset Turnover,Inventory Turnover Ratio,Receiveable Turnover,Days Sales In Receivables,ROE - Return On Equity,Return On Tangible Equity,ROA - Return On Assets,ROI - Return On Investment,Book Value Per Share,Operating Cash Flow Per Share,Free Cash Flow Per Share
Date,,,,,,,,,,,,,,,,,,,,
2005-09-30,2.9538,NaN,NaN,29.0144,11.7938,11.7938,13.0787,12.9783,9.5327,1.2097,59.9333,15.5654,23.4495,17.8783,18.1124,11.5318,17.8783,1.2708,0.4226,0.3793
2006-09-30,2.2519,NaN,NaN,28.9827,12.7000,12.7000,13.8649,14.5897,10.2977,1.1226,50.8037,15.4273,23.6593,19.9219,20.2814,11.5606,19.9219,1.6677,0.3614,0.2544
2007-09-30,2.3659,NaN,NaN,33.1679,17.9307,17.9307,19.2611,20.3678,14.2200,0.9697,47.4740,15.0141,24.3106,24.0504,24.6214,13.7886,24.0504,2.3798,0.8787,0.7606
2008-09-30,2.6411,NaN,NaN,35.2005,22.2107,22.2107,23.5337,23.8644,16.3213,1.0365,47.7289,15.4794,23.5798,27.4432,28.0624,16.9169,27.4432,3.5857,1.5196,1.3468
2009-09-30,2.7425,NaN,NaN,40.1399,27.3628,27.3628,29.0735,28.1226,19.1936,0.9032,56.4462,8.4843,43.0207,26.0272,26.4052,17.3365,26.0272,5.0233,1.6001,1.4199
2010-09-30,2.0113,NaN,NaN,39.3775,28.1871,28.1871,29.7616,28.4247,21.4841,0.8675,37.6223,6.5725,55.5348,29.3214,30.0013,18.6385,29.3214,7.4536,2.8727,2.5630
2011-09-30,1.6084,NaN,NaN,40.4789,31.2151,31.2151,32.8908,31.5985,23.9466,0.9302,83.0296,9.2386,39.5080,33.8341,35.9115,22.2753,33.8341,11.7780,5.7239,5.0742
2012-09-30,1.4958,NaN,NaN,43.8712,35.2960,35.2960,37.3898,35.6295,26.6651,0.8889,111.0569,8.3730,43.5925,35.3041,36.9806,23.7033,35.3041,17.9802,7.6851,6.4316
2013-09-30,1.6786,0.1207,0.1373,37.6245,28.6695,28.6695,32.6230,29.3459,21.6705,0.8257,60.4342,8.2801,44.0815,29.9776,31.4425,17.8923,26.3592,19.6281,8.2289,6.9769
2014-09-30,1.0801,0.2063,0.3164,38.5880,28.7223,28.7223,33.0693,29.2585,21.6144,0.7885,53.1776,6.7157,54.3501,35.4201,38.4380,17.0420,28.1142,19.0153,9.7528,8.1896
2015-09-30,1.1088,0.3088,0.5390,40.0599,30.4773,30.4773,35.2938,31.0271,22.8458,0.8050,59.6377,7.7024,47.3876,44.7355,48.3878,18.3899,30.9201,21.3946,14.0281,12.0867
2016-09-30,1.3527,0.3703,0.6786,39.0760,27.8354,27.8354,32.7070,28.4605,21.1868,0.6703,61.6210,7.3599,49.5928,35.6237,38.1906,14.2024,22.4312,24.0339,12.0414,9.7262
2017-09-30,1.2761,0.4203,0.8630,38.4699,26.7604,26.7604,31.1913,27.9579,21.0924,0.6108,29.0521,6.4260,56.8007,36.0702,36.0702,12.8826,20.9082,26.1494,12.2294,9.8585
2018-09-30,1.1329,0.4666,1.0685,38.3437,26.6940,26.6940,30.7992,27.4489,22.4142,0.7262,41.3943,5.4209,67.3325,55.5601,55.5601,16.2775,29.6348,22.5336,15.4865,12.8239
2019-09-30,1.5401,0.5036,1.1940,37.8178,24.5720,24.5720,29.3946,25.2666,21.2381,0.7686,39.4014,5.6802,64.2588,61.0645,61.0645,16.3230,30.3113,20.3653,14.9263,12.6688

In [10]:
aapl_func = aapl.get_funcdamental_data()
aapl_func

,Cash On Hand,Receivables,Inventory,Pre-Paid Expenses,Other Current Assets,Total Current Assets,"Property, Plant, And Equipment",Long-Term Investments,Goodwill And Intangible Assets,Other Long-Term Assets,...,Inventory Turnover Ratio,Receiveable Turnover,Days Sales In Receivables,ROE - Return On Equity,Return On Tangible Equity,ROA - Return On Assets,ROI - Return On Investment,Book Value Per Share,Operating Cash Flow Per Share,Free Cash Flow Per Share
Date,,,,,,,,,,,,,,,,,,,,,
2005-03-31,7057.0,888.0,164.0,None,601.0,9007.0,742.0,NaN,113.0,249.0,...,13.8720,3.6520,24.6439,4.5412,4.6230,2.8682,4.5412,1.1083,0.2185,0.2017
2005-06-30,7526.0,827.0,193.0,None,496.0,9376.0,764.0,NaN,109.0,239.0,...,12.8290,4.2563,21.1449,4.6767,4.7527,3.0416,4.6767,1.1769,0.2959,0.2687
2005-09-30,8261.0,895.0,165.0,None,648.0,10300.0,817.0,NaN,96.0,303.0,...,16.0242,4.1095,21.9005,5.7081,5.7829,3.6818,5.7081,1.2708,0.4226,0.3793
2005-12-31,8707.0,1331.0,244.0,None,1409.0,12162.0,855.0,NaN,93.0,1071.0,...,17.1516,4.3193,20.8367,6.7422,6.8179,3.9842,6.7422,1.4157,0.0462,0.0328
2006-03-31,8226.0,861.0,204.0,None,1536.0,11286.0,1005.0,NaN,110.0,1510.0,...,15.0098,5.0627,17.7770,4.7224,4.7830,2.9473,4.7224,1.4606,0.0257,-0.0190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-31,80092.0,26278.0,4884.0,None,12092.0,123346.0,38746.0,145319.0,NaN,34587.0,...,7.4107,2.2077,40.7657,10.9210,10.9210,3.3804,5.8966,22.9767,8.0510,6.8346
2019-06-30,94614.0,26474.0,3355.0,None,10530.0,134973.0,37636.0,115996.0,NaN,33634.0,...,10.0095,2.0325,44.2800,10.4130,10.4130,3.1169,5.5372,21.2862,10.7535,9.0762
2019-09-30,100557.0,45804.0,4106.0,None,12352.0,162819.0,37378.0,105341.0,NaN,32978.0,...,9.6754,1.3981,64.3716,15.1247,15.1247,4.0429,7.5076,20.3653,14.9263,12.6688
2019-12-31,107162.0,39946.0,4097.0,None,12026.0,163231.0,37031.0,99899.0,NaN,40457.0,...,13.8155,2.2986,39.1546,24.8361,24.8361,6.5281,12.1768,20.4178,6.8504,6.3774
2020-03-31,94051.0,30677.0,3334.0,None,15691.0,143753.0,35889.0,98793.0,NaN,41965.0,...,10.7807,1.9009,47.3467,14.3436,14.3436,3.5109,6.7154,18.1372,9.9501,9.0510

In [11]:
aapl_func.columns

Index(['Cash On Hand', 'Receivables', 'Inventory', 'Pre-Paid Expenses',
       'Other Current Assets', 'Total Current Assets',
       'Property, Plant, And Equipment', 'Long-Term Investments',
       'Goodwill And Intangible Assets', 'Other Long-Term Assets',
       'Total Long-Term Assets', 'Total Assets', 'Total Current Liabilities',
       'Long Term Debt', 'Other Non-Current Liabilities',
       'Total Long Term Liabilities', 'Total Liabilities', 'Common Stock Net',
       'Retained Earnings (Accumulated Deficit)', 'Comprehensive Income',
       'Other Share Holders Equity', 'Share Holder Equity',
       'Total Liabilities And Share Holders Equity', 'Revenue',
       'Cost Of Goods Sold', 'Gross Profit',
       'Research And Development Expenses', 'SG&A Expenses',
       'Other Operating Income Or Expenses', 'Operating Expenses',
       'Operating Income', 'Total Non-Operating Income/Expense',
       'Pre-Tax Income', 'Income Taxes', 'Income After Taxes', 'Other Income',
       'Income From Continuous Operations',
       'Income From Discontinued Operations', 'Net Income', 'EBITDA', 'EBIT',
       'Basic Shares Outstanding', 'Shares Outstanding', 'Basic EPS',
       'EPS - Earnings Per Share', 'Net Income/Loss',
       'Total Depreciation And Amortization - Cash Flow',
       'Other Non-Cash Items', 'Total Non-Cash Items',
       'Change In Accounts Receivable', 'Change In Inventories',
       'Change In Accounts Payable', 'Change In Assets/Liabilities',
       'Total Change In Assets/Liabilities',
       'Cash Flow From Operating Activities',
       'Net Change In Property, Plant, And Equipment',
       'Net Change In Intangible Assets', 'Net Acquisitions/Divestitures',
       'Net Change In Short-term Investments',
       'Net Change In Long-Term Investments',
       'Net Change In Investments - Total', 'Investing Activities - Other',
       'Cash Flow From Investing Activities', 'Net Long-Term Debt',
       'Net Current Debt', 'Debt Issuance/Retirement Net - Total',
       'Net Common Equity Issued/Repurchased',
       'Net Total Equity Issued/Repurchased',
       'Total Common And Preferred Stock Dividends Paid',
       'Financial Activities - Other', 'Cash Flow From Financial Activities',
       'Net Cash Flow', 'Stock-Based Compensation',
       'Common Stock Dividends Paid', 'Current Ratio',
       'Long-term Debt / Capital', 'Debt/Equity Ratio', 'Gross Margin',
       'Operating Margin', 'EBIT Margin', 'EBITDA Margin',
       'Pre-Tax Profit Margin', 'Net Profit Margin', 'Asset Turnover',
       'Inventory Turnover Ratio', 'Receiveable Turnover',
       'Days Sales In Receivables', 'ROE - Return On Equity',
       'Return On Tangible Equity', 'ROA - Return On Assets',
       'ROI - Return On Investment', 'Book Value Per Share',
       'Operating Cash Flow Per Share', 'Free Cash Flow Per Share'],
      dtype='object')